# Rose Pine Dawn Colours
#
# base            '#faf4ed'  (lightest bg)
# surface         '#fffaf3'
# overlay         '#f2e9e1'
# muted           '#9893a5'
# subtle          '#797593'
# text            '#575279'  (dark content)
# love            '#b4637a'  (red/pink)
# gold            '#ea9d34'  (yellow)
# rose            '#d7827e'
# pine            '#286983'  (blue/teal)
# foam            '#56949f'  (cyan)
# iris            '#907aa9'  (purple/magenta)
# highlight-low   '#f4ede8'
# highlight-med   '#dfdad9'
# highlight-high  '#cecacd'

setw -g mode-style fg="default",bg="#f2e9e1"

set -g status-style bg="#faf4ed",fg="#907aa9"
setw -g status-left-style fg="#faf4ed",bg="#907aa9"

set -g status-right "#(tmux-k8s-current-context) #(gitmux -cfg $HOME/.dotfiles/tmux/gitmux-light.conf \"#{pane_current_path}\") #[bg=#f2e9e1,fg=#575279] %a %B %-d, %Y #[fg=#56949f].:. #[fg=#575279]%H:%M "

set-environment -g DELTA_THEME "GitHub"

setw -g status-left " #S "
setw -g window-status-format " #I: #W "
setw -g window-status-separator ""
setw -g window-status-style fg="#575279"

setw -g window-status-current-format "#[fg=#faf4ed]#[bg=#286983] #I: #W "
setw -g window-status-activity-style fg="#575279",bg="#f2e9e1"

set -g window-style 'fg=#797593,bg=#f2e9e1'
set -g window-active-style 'fg=#575279,bg=#faf4ed'

set -g pane-border-style 'fg=#9893a5'
set -g pane-active-border-style 'fg=#575279'
